# Generated by Django 2.1.5 on 2019-01-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190117_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallist',
            name='following',
        ),
        migrations.RemoveField(
            model_name='sociallist',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_profile_friends_+', to='users.Profile'),
        ),
    ]
