# Generated by Django 2.1.5 on 2019-01-18 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_auto_20190117_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverImage', models.ImageField(default='default_cover.jpg', upload_to='cover_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sociallist',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.DeleteModel(
            name='SocialList',
        ),
    ]
