# Generated by Django 2.1.5 on 2019-01-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190117_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='coverImage',
            field=models.ImageField(default='default_cover.png', upload_to='cover_pics'),
        ),
    ]
