# Generated by Django 2.1.5 on 2019-01-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190118_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='about',
            field=models.CharField(default='Write about yourself.', max_length=160),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='quote',
            field=models.CharField(default='Write an original idea!', max_length=80),
        ),
    ]
