# Generated by Django 2.1.5 on 2019-02-09 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190123_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
