# Generated by Django 2.1.5 on 2019-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_date_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_send_feedback',
            field=models.BooleanField(default=True),
        ),
    ]
