# Generated by Django 2.1.5 on 2019-02-11 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_profile_can_send_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('quality_speed', models.CharField(choices=[('F', 'Unacceptable'), ('D', 'Needs Work'), ('C', 'Neutral'), ('B', 'Pleased'), ('A', 'Very Pleased')], default='C', max_length=1)),
                ('quality_features', models.CharField(choices=[('F', 'Unacceptable'), ('D', 'Needs Work'), ('C', 'Neutral'), ('B', 'Pleased'), ('A', 'Very Pleased')], default='C', max_length=1)),
                ('quality_visual', models.CharField(choices=[('F', 'Unacceptable'), ('D', 'Needs Work'), ('C', 'Neutral'), ('B', 'Pleased'), ('A', 'Very Pleased')], default='C', max_length=1)),
                ('quality_stability', models.CharField(choices=[('F', 'Unacceptable'), ('D', 'Needs Work'), ('C', 'Neutral'), ('B', 'Pleased'), ('A', 'Very Pleased')], default='C', max_length=1)),
                ('quality_responsiveness', models.CharField(choices=[('F', 'Unacceptable'), ('D', 'Needs Work'), ('C', 'Neutral'), ('B', 'Pleased'), ('A', 'Very Pleased')], default='C', max_length=1)),
                ('comment', models.CharField(max_length=300)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
