# Generated by Django 2.1.5 on 2019-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='quality_features',
            field=models.CharField(blank=True, choices=[('0', 'Select an option'), ('F', 'Unacceptable'), ('D', 'Needs Work'), ('C', 'Neutral'), ('B', 'Pleased'), ('A', 'Very Pleased')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='quality_responsiveness',
            field=models.CharField(blank=True, choices=[('0', 'Select an option'), ('F', 'Unacceptable'), ('D', 'Needs Work'), ('C', 'Neutral'), ('B', 'Pleased'), ('A', 'Very Pleased')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='quality_speed',
            field=models.CharField(blank=True, choices=[('0', 'Select an option'), ('F', 'Unacceptable'), ('D', 'Needs Work'), ('C', 'Neutral'), ('B', 'Pleased'), ('A', 'Very Pleased')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='quality_stability',
            field=models.CharField(blank=True, choices=[('0', 'Select an option'), ('F', 'Unacceptable'), ('D', 'Needs Work'), ('C', 'Neutral'), ('B', 'Pleased'), ('A', 'Very Pleased')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='quality_visual',
            field=models.CharField(blank=True, choices=[('0', 'Select an option'), ('F', 'Unacceptable'), ('D', 'Needs Work'), ('C', 'Neutral'), ('B', 'Pleased'), ('A', 'Very Pleased')], default='0', max_length=1),
        ),
    ]
