# Generated by Django 2.1.5 on 2019-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190211_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='about',
            field=models.CharField(blank=True, default=None, max_length=160),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='quote',
            field=models.CharField(blank=True, default=None, max_length=80),
        ),
    ]
