# Generated by Django 2.1.5 on 2019-02-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190213_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='about',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='quote',
            field=models.CharField(default='', max_length=80),
        ),
    ]
