# Generated by Django 2.1.5 on 2019-02-14 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0021_auto_20190213_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('nick', models.CharField(default='New Group', max_length=20)),
                ('image', models.ImageField(default='default_profile.jpg', upload_to='profile_pics')),
                ('date_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('private', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(blank=True, related_name='_group_members_+', to='users.Group')),
                ('mods', models.ManyToManyField(blank=True, related_name='_group_mods_+', to='users.Group')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverImage', models.ImageField(default='default_cover.png', upload_to='cover_pics')),
                ('about', models.CharField(blank=True, default='', max_length=160)),
                ('quote', models.CharField(blank=True, default='', max_length=80)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='nick',
            field=models.CharField(default='New User', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='about',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='quote',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
