# Generated by Django 2.1.5 on 2019-02-14 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190214_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='mods',
            field=models.ManyToManyField(blank=True, related_name='mods', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
