# Generated by Django 2.1.5 on 2019-02-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190214_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='mods',
        ),
    ]
