# Generated by Django 2.1.5 on 2019-02-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_group_mods'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mods',
            field=models.ManyToManyField(blank=True, related_name='mods', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='users.Profile'),
        ),
    ]
