# Generated by Django 2.1.5 on 2019-02-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20190215_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Public'), ('3', 'Private')], default='2', max_length=1),
        ),
    ]
