# Generated by Django 2.1.5 on 2019-02-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Public'), ('3', 'Public Invite-Only'), ('4', 'Private'), ('5', 'Private Invite-Only')], default='2', max_length=1),
        ),
    ]
