# Generated by Django 2.1.5 on 2019-02-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_group_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
