# Generated by Django 2.1.5 on 2019-01-27 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reply',
            field=models.ForeignKey(blank=True, default='self', on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
