# Generated by Django 2.1.5 on 2019-01-31 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190127_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reply',
            field=models.ForeignKey(blank=True, default='self', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
