# Generated by Django 2.1.5 on 2019-03-01 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20190301_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='post_pics')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_files', verbose_name='Video')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio_files', verbose_name='Audio')),
                ('content', models.TextField(blank=True, max_length=500)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('people', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('recepient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_recepient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(blank=True, to='blog.Topic')),
            ],
        ),
    ]
