# Generated by Django 2.1.5 on 2019-03-01 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_message_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recepient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgrecepient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgsender', to=settings.AUTH_USER_MODEL),
        ),
    ]
