# Generated by Django 2.1.5 on 2019-02-04 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190203_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='blog.Post'),
        ),
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
