# Generated by Django 2.1.5 on 2019-02-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_notification_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='confirm',
            new_name='confirmed',
        ),
    ]
