# Generated by Django 2.1.5 on 2019-02-04 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190204_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
