# Generated by Django 2.1.5 on 2019-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_notification_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='accepted_request',
            field=models.BooleanField(default=False),
        ),
    ]
