# Generated by Django 2.1.5 on 2019-02-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_notification_accepted_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='accepted_request',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
