# Generated by Django 2.1.5 on 2019-02-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190204_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
