# Generated by Django 2.1.5 on 2019-02-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_request_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='link',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='message',
        ),
    ]
