# Generated by Django 2.1.5 on 2019-02-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190206_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='first_seen',
            field=models.BooleanField(default=False),
        ),
    ]
