# Generated by Django 2.1.5 on 2019-02-08 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_notification_first_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
