# Generated by Django 2.1.5 on 2019-02-12 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='approved',
            new_name='confirmed',
        ),
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
        migrations.RemoveField(
            model_name='report',
            name='post',
        ),
        migrations.RemoveField(
            model_name='report',
            name='type',
        ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='report',
            name='report_illicit',
            field=models.CharField(choices=[('1', 'Offensive/Abusive Material'), ('2', 'Illicit Material'), ('3', 'Personal Threats'), ('4', 'Security Concern'), ('5', 'Spam')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='report',
            name='report_offensive',
            field=models.CharField(choices=[('1', 'Offensive/Abusive Material'), ('2', 'Illicit Material'), ('3', 'Personal Threats'), ('4', 'Security Concern'), ('5', 'Spam')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='report',
            name='report_security',
            field=models.CharField(choices=[('1', 'Offensive/Abusive Material'), ('2', 'Illicit Material'), ('3', 'Personal Threats'), ('4', 'Security Concern'), ('5', 'Spam')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='report',
            name='report_spam',
            field=models.CharField(choices=[('1', 'Offensive/Abusive Material'), ('2', 'Illicit Material'), ('3', 'Personal Threats'), ('4', 'Security Concern'), ('5', 'Spam')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='report',
            name='report_threat',
            field=models.CharField(choices=[('1', 'Offensive/Abusive Material'), ('2', 'Illicit Material'), ('3', 'Personal Threats'), ('4', 'Security Concern'), ('5', 'Spam')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
