# Generated by Django 2.1.5 on 2019-02-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190211_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_illicit',
            new_name='report_choice',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_offensive',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_security',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_spam',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_threat',
        ),
    ]
