# Generated by Django 2.1.5 on 2019-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_report_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_choice',
            field=models.CharField(choices=[('1', 'Offensive/Abusive Material'), ('2', 'Illicit Material'), ('3', 'Personal Threats'), ('4', 'Security Concern'), ('5', 'Spam')], max_length=1),
        ),
    ]
