# Generated by Django 2.1.5 on 2019-02-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20190215_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
