# Generated by Django 2.1.5 on 2019-02-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20190214_1719'),
        ('blog', '0028_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='type',
        ),
        migrations.AddField(
            model_name='request',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Group'),
        ),
    ]
